name: Android Build

on:
  push:
    branches: [main, feat/upgrade-react-native3]
    paths: ['visa_manager_frontend/**']
  pull_request:
    branches: [main]
    paths: ['visa_manager_frontend/**']

jobs:
  android-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./visa_manager_frontend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: visa_manager_frontend/yarn.lock

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            visa_manager_frontend/android/.gradle
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test --watchAll=false

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          WS_URL: ${{ secrets.WS_URL }}
          CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: visa_manager_frontend/android/app/build/outputs/apk/release/

  android-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./visa_manager_frontend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run unit tests
        run: yarn test --watchAll=false --coverage

      - name: Run E2E tests
        run: yarn test:e2e

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            visa_manager_frontend/coverage/
            visa_manager_frontend/__tests__/results/